name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          start: npx cypress run
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
        
